### ISSUE TITLE
No instructions for how to load *.csv files into tables.

### ISSUE THREAD

**Issue by itohiro73** [goldmansachs/obevo-kata#5]
Following set-up and lesson 1 kata instruction, I couldn't find any instructions on how to load the *.csv files under data folder.

I find ${tableAsStringFieldName} variable in TABLE_A.csv file, so I guessed obevo may support loading them using some command or something.

Please kindly advise.

**Comment by shantstepanian** [comment]
I've committed a fix to the kata. Please try again.

Background: the CSV files need to be in the /staticdata folder, not /data (see [here](https://goldmansachs.github.io/obevo/db-project-structure.html#Managing_Static_Data__Code_Tables)). /data was the previous convention that we don't want to support for new clients

**Comment by itohiro73** [comment]
This worked fine now. Thanks for your prompt action!
